/**
 * Decides which third-party source files are committed, so a fresh clone can
 * run `pnpm assets:build && pnpm media:build` without downloading any pack.
 *
 *   pnpm assets:vendor          writes art/third_party/.gitignore (allowlist)
 *   pnpm assets:vendor --check  exits 1 when the allowlist is out of date
 *
 * Kept: every file an approved pack's SOURCE.json references —
 * models (+ their .bin buffers and images), animation sources, grafted parts,
 * texture folders, converted GLBs and media — and nothing else, so the large
 * unused remainder of each pack stays local.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, posix, relative, resolve } from 'node:path';
import { PackSourceSchema } from './source';

const thirdParty = resolve(import.meta.dirname, '../../art/third_party');
const out = join(thirdParty, '.gitignore');
const keep = new Set<string>();
const missing: string[] = [];
let bytes = 0;

const rel = (abs: string) => relative(thirdParty, abs).split('\\').join('/');
function add(abs: string): void {
  if (!existsSync(abs)) {
    missing.push(rel(abs));
    return;
  }
  const r = rel(abs);
  // Only files under originals/ or converted/ need allowlisting.
  if (!/^[^/]+\/(originals|converted)\//.test(r) || keep.has(r)) return;
  keep.add(r);
  bytes += statSync(abs).size;
}

/** A model file plus what a .gltf points at (buffers, images). */
function addModel(abs: string, textureDirs: readonly string[] = []): void {
  add(abs);
  if (!abs.toLowerCase().endsWith('.gltf') || !existsSync(abs)) return;
  const gltf = JSON.parse(readFileSync(abs, 'utf8')) as {
    buffers?: { uri?: string }[];
    images?: { uri?: string }[];
  };
  for (const ref of [...(gltf.buffers ?? []), ...(gltf.images ?? [])]) {
    if (!ref.uri || ref.uri.startsWith('data:')) continue;
    const uri = decodeURIComponent(ref.uri);
    const local = join(dirname(abs), uri);
    if (existsSync(local)) {
      add(local);
      continue;
    }
    // Images may be resolved through textureDirs by the build.
    const found = textureDirs
      .map((d) => join(dirname(abs), d, posix.basename(uri)))
      .find((p) => existsSync(p));
    if (found) add(found);
    else missing.push(`${rel(abs)} → ${uri}`);
  }
}

for (const dir of readdirSync(thirdParty, { withFileTypes: true })) {
  if (!dir.isDirectory()) continue;
  const packDir = join(thirdParty, dir.name);
  const sourcePath = join(packDir, 'SOURCE.json');
  if (!existsSync(sourcePath)) continue;
  const pack = PackSourceSchema.parse(JSON.parse(readFileSync(sourcePath, 'utf8')));
  // Only what the game can use: rejected and prototype-only packs stay local.
  if (pack.status !== 'approved') continue;
  for (const asset of pack.assets) {
    addModel(join(packDir, asset.file), asset.textureDirs);
    const sources =
      typeof asset.animationSource === 'string'
        ? [asset.animationSource]
        : (asset.animationSource ?? []);
    for (const s of sources) addModel(join(packDir, s));
    for (const part of asset.parts) addModel(join(packDir, part.file), part.textureDirs);
  }
  for (const m of pack.media) add(join(packDir, m.file));
}

const lines = [
  '# Generated by `pnpm assets:vendor` — do not edit by hand.',
  '# Pack originals stay local except the files the game needs (SOURCE.json references).',
  '*/originals/**',
  '*/converted/**',
  '!*/originals/**/',
  '!*/converted/**/',
  ...[...keep].sort().map((p) => `!/${p.replace(/([ #!*?[\]])/g, '\\$1')}`),
  '',
];
const text = lines.join('\n');

if (missing.length) {
  console.error(`missing (download the pack or fix SOURCE.json):\n  ${missing.join('\n  ')}`);
}
if (process.argv.includes('--check')) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (current !== text) {
    console.error('art/third_party/.gitignore is out of date — run `pnpm assets:vendor`');
    process.exit(1);
  }
  console.log(`vendor list up to date (${keep.size} files)`);
} else {
  writeFileSync(out, text);
  console.log(
    `${keep.size} files (${(bytes / 1024 / 1024).toFixed(1)} MB) allowlisted → ${rel(out)}`,
  );
}
process.exit(0);
